services:
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: mini-airbnb-meilisearch
    ports:
      - '7700:7700'
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_ENV=development
    volumes:
      - meilisearch_data:/meili_data

volumes:
  meilisearch_data:
